<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Tommy" failures="1" tests="1" name="Error Validation" time="13.02" errors="0" timestamp="2023-11-03T21:53:08 WIB">
  <testcase classname="org.Appium.errorValidation" name="homeErrorValidation" time="3.723">
    <failure type="java.lang.AssertionError" message="expected [Please enter your name!] but found [Please enter your name]">
      <![CDATA[java.lang.AssertionError: expected [Please enter your name!] but found [Please enter your name]
at org.Appium.errorValidation.homeErrorValidation(errorValidation.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- homeErrorValidation -->
</testsuite> <!-- Error Validation -->
